### ISSUE TITLE
Build failing on latest master

### ISSUE THREAD

**Issue by varunu28** [brianshih1/mini-key-value-db#10]
With latest master(Commit: [d0f4950377cf6f91664d4b098ede06d89d597e0e](https://github.com/brianshih1/mini-key-value-db/commit/d0f4950377cf6f91664d4b098ede06d89d597e0e)), running `cargo test` results in multiple failures(On Mac M1)
```
test result: FAILED. 63 passed; 38 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.20s
```

Next steps should be to fix these test cases & add a Github workflow that runs with every PR to run `cargo test` in order to verify that build remains green

**Comment by varunu28** [comment]
@brianshih1 I will be happy to work on this issue

**Comment by brianshih1** [comment]
thanks for the catch! Would be awesome if you could add the workflow or fix some tests. I'll also take a look at the failing tests sometime next week!

**Comment by brianshih1** [comment]
Currently the test works if it runs via a single thread: `cargo test -- --test-threads=1`.  This is because the tests currently share and clear the same directory: `Arc::new(DB::new_cleaned("./tmp/data"`

**Comment by brianshih1** [comment]
Just merged a commit to generate a random path for each test `DB` instance. I created another task to clean up the test files created by unit tests here: https://github.com/brianshih1/mini-key-value-db/issues/12

**Comment by brianshih1** [comment]
Just added a github workflow to run `cargo build` and `cargo test`!
