### ISSUE TITLE
Clean up test DB files created from unit tests

### ISSUE THREAD

**Issue by brianshih1** [brianshih1/mini-key-value-db#12]
In our unit tests, we use `DB::new_random_path` to create random DB instances pointing at `/tmp/{random_string}`. We should clean that up.

**Comment by varunu28** [comment]
This can be resolved using temporary directories that get cleaned up with each test. Some reference: https://andrewra.dev/2019/03/01/testing-in-rust-temporary-files/

I will be happy to work on this if you have not already started. Feel free to assign the issue to me.

**Comment by brianshih1** [comment]
that would be great, thanks!!
